# Generated by Django 5.2.6 on 2025-10-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meds',
            options={'verbose_name_plural': 'Meds'},
        ),
        migrations.AddField(
            model_name='meds',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
